POST http://localhost:3000/register
Content-Type: application/json

    {
        "firstName": "Wawan",
        "lastName": "Jamalludin",
        "email": "Syizwan.Jamalludin@gmail.com",
        "password": "wawan2eyh"
    }

POST http://localhost:3000/register
Content-Type: application/json

    {
        "firstName": "James",
        "lastName": "Dean",
        "email": "Dean.James@gmail.com",
        "password": "Dean2eyh"
    }

POST http://localhost:3000/login
Content-Type: application/json

    {
        "email": "Syizwan.Jamalludin@gmail.com",
        "password": "wawan2eyh"
    }

POST http://localhost:3000/login
Content-Type: application/json

    {
        "email": "Dean.James@gmail.com",
        "password": "Dean2eyh"
    } 

GET http://localhost:3000/all-users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTU5MzE3Mzg4M30.JZvGNZhhmlywlRPQPZZmqVYf6I6TP5ClJp-SP3srfwI


GET http://localhost:3000/user/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImlhdCI6MTU5MzE3Mzg4M30.JZvGNZhhmlywlRPQPZZmqVYf6I6TP5ClJp-SP3srfwI

GET http://localhost:3000/my-profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjUsImlhdCI6MTU5MzE3Nzc2Mn0.Nao08Mgh0NEmbA-yqXlZA2sqMXScPWtDspUdhs7tlAE